document.addEventListener("DOMContentLoaded", () => {
  const urlInput = document.getElementById("scrape-url");
  const btnTest = document.getElementById("btn-test");
  const codeSnippet = document.getElementById("code-snippet");
  const markdownOutput = document.getElementById("markdown-output");
  const outputBadge = document.getElementById("output-badge");
  const langBtns = document.querySelectorAll(".lang-btn");
  const btnCopyCode = document.getElementById("btn-copy-code");

  let currentLang = "python";

  const codeGenerators = {
    python: (url) => `# Python Requests Example
import requests

url = "https://smart-markdown-web-scraper.p.rapidapi.com/scrape"
payload = { "url": "${url}" }
headers = {
    "x-rapidapi-key": "YOUR_RAPIDAPI_KEY",
    "x-rapidapi-host": "smart-markdown-web-scraper.p.rapidapi.com",
    "Content-Type": "application/json"
}

response = requests.post(url, json=payload, headers=headers)
print(response.json()["markdown"])`,

    javascript: (url) => `// Node.js Fetch Example
const fetch = require('node-fetch');

async function scrape() {
  const res = await fetch("https://smart-markdown-web-scraper.p.rapidapi.com/scrape", {
    method: "POST",
    headers: {
      "x-rapidapi-key": "YOUR_RAPIDAPI_KEY",
      "x-rapidapi-host": "smart-markdown-web-scraper.p.rapidapi.com",
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ url: "${url}" })
  });

  const data = await res.json();
  console.log(data.markdown);
}

scrape();`,

    curl: (url) => `# cURL Command
curl --request POST \\
  --url https://smart-markdown-web-scraper.p.rapidapi.com/scrape \\
  --header 'Content-Type: application/json' \\
  --header 'x-rapidapi-host: smart-markdown-web-scraper.p.rapidapi.com' \\
  --header 'x-rapidapi-key: YOUR_RAPIDAPI_KEY' \\
  --data '{"url":"${url}"}'`,

    langchain: (url) => `# LangChain Document Loader
from integrations.langchain_loader import SmartMarkdownWebLoader

loader = SmartMarkdownWebLoader(
    urls=["${url}"],
    rapidapi_key="YOUR_RAPIDAPI_KEY"
)

docs = loader.load()
print(docs[0].page_content[:500])`
  };

  function updateSnippet() {
    const targetUrl = urlInput.value.trim() || "https://news.ycombinator.com";
    if (codeGenerators[currentLang]) {
      codeSnippet.textContent = codeGenerators[currentLang](targetUrl);
    }
  }

  langBtns.forEach((btn) => {
    btn.addEventListener("click", () => {
      langBtns.forEach((b) => b.classList.remove("active"));
      btn.classList.add("active");
      currentLang = btn.getAttribute("data-lang");
      updateSnippet();
    });
  });

  urlInput.addEventListener("input", updateSnippet);

  // Copy Code Action
  if (btnCopyCode) {
    btnCopyCode.addEventListener("click", async () => {
      await navigator.clipboard.writeText(codeSnippet.textContent);
      const origText = btnCopyCode.textContent;
      btnCopyCode.textContent = "Copied!";
      setTimeout(() => (btnCopyCode.textContent = origText), 1800);
    });
  }

  // Live Scrape Simulator
  btnTest.addEventListener("click", () => {
    const targetUrl = urlInput.value.trim();
    if (!targetUrl) return;

    outputBadge.textContent = "Processing...";
    outputBadge.style.color = "var(--cyan)";
    btnTest.textContent = "Scraping...";

    setTimeout(() => {
      outputBadge.textContent = "200 OK";
      outputBadge.style.color = "var(--emerald)";
      btnTest.textContent = "Run Scrape";

      markdownOutput.textContent = `# Scraped Document: ${targetUrl}

## Overview
Clean Markdown output generated by **Smart Markdown Web Scraper API**.

### Extracted Highlights:
- Removed navigation headers, tracking scripts, and sidebars.
- Structured article headings (H1-H3) and paragraphs cleanly.
- Saved approx **1,420 tokens** for downstream LLM prompts.

\`\`\`json
{
  "status": "success",
  "source_url": "${targetUrl}",
  "tokens_saved_estimate": 1420,
  "execution_time_ms": 215
}
\`\`\`

> *Subscribe on RapidAPI Hub to run live API calls against any URL!*`;
    }, 550);
  });

  updateSnippet();
});
