document.addEventListener("DOMContentLoaded", () => {
  const urlInput = document.getElementById("scrape-url");
  const btnTest = document.getElementById("btn-test");
  const codeSnippet = document.getElementById("code-snippet");
  const markdownOutput = document.getElementById("markdown-output");
  const outputBadge = document.getElementById("output-badge");
  const langTabs = document.querySelectorAll(".lang-tab");

  let currentLang = "python";

  const codeSnippets = {
    python: (url) => `# Python Requests Example
import requests

url = "https://smart-markdown-web-scraper.p.rapidapi.com/scrape"
payload = { "url": "${url}" }
headers = {
    "x-rapidapi-key": "YOUR_RAPIDAPI_KEY",
    "x-rapidapi-host": "smart-markdown-web-scraper.p.rapidapi.com",
    "Content-Type": "application/json"
}

response = requests.post(url, json=payload, headers=headers)
print(response.json()["markdown"])`,

    javascript: (url) => `// Node.js Fetch Example
const fetch = require('node-fetch');

async function scrape() {
  const res = await fetch("https://smart-markdown-web-scraper.p.rapidapi.com/scrape", {
    method: "POST",
    headers: {
      "x-rapidapi-key": "YOUR_RAPIDAPI_KEY",
      "x-rapidapi-host": "smart-markdown-web-scraper.p.rapidapi.com",
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ url: "${url}" })
  });

  const data = await res.json();
  console.log(data.markdown);
}

scrape();`,

    curl: (url) => `# cURL Command
curl --request POST \\
  --url https://smart-markdown-web-scraper.p.rapidapi.com/scrape \\
  --header 'Content-Type: application/json' \\
  --header 'x-rapidapi-host: smart-markdown-web-scraper.p.rapidapi.com' \\
  --header 'x-rapidapi-key: YOUR_RAPIDAPI_KEY' \\
  --data '{"url":"${url}"}'`
  };

  function updateCodeSnippet() {
    const targetUrl = urlInput.value.trim() || "https://news.ycombinator.com";
    if (codeSnippets[currentLang]) {
      codeSnippet.textContent = codeSnippets[currentLang](targetUrl);
    }
  }

  // Handle Tab Switching
  langTabs.forEach((tab) => {
    tab.addEventListener("click", () => {
      langTabs.forEach((t) => t.classList.remove("active"));
      tab.classList.add("active");
      currentLang = tab.getAttribute("data-lang");
      updateCodeSnippet();
    });
  });

  urlInput.addEventListener("input", updateCodeSnippet);

  // Simulate API Call for Playground
  btnTest.addEventListener("click", () => {
    const targetUrl = urlInput.value.trim();
    if (!targetUrl) return;

    outputBadge.textContent = "Processing...";
    outputBadge.style.borderColor = "var(--primary)";
    outputBadge.style.color = "var(--primary)";
    btnTest.textContent = "Scraping...";

    setTimeout(() => {
      outputBadge.textContent = "Scraped Success (200 OK)";
      outputBadge.className = "badge badge-success";
      btnTest.textContent = "Scrape Markdown";

      markdownOutput.textContent = `# Scraped Document: ${targetUrl}

## Overview
This is a simulated preview of the clean Markdown output generated by **Smart Markdown Web Scraper API**.

### Extracted Highlights:
- Stripped 14 navigation links, 6 advertisement banners, and 3 footer menus.
- Extracted core body text and converted tables/headings cleanly.
- Saved approx **1,420 tokens** for downstream LLM prompts (GPT-4 / Claude).

\`\`\`json
{
  "status": "success",
  "source_url": "${targetUrl}",
  "tokens_saved_estimate": 1420,
  "execution_time_ms": 210
}
\`\`\`

> *Subscribe on RapidAPI to run live calls against real target URLs!*`;
    }, 600);
  });

  updateCodeSnippet();
});
